---
title: "Data set up"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Below is the code used to previously get the data into a working data set.

```{r}
library(tidyverse)

maternity_df <- read.csv("data/Maternity.csv")

maternity_df <- maternity_df %>% mutate(Measure.Name = as.character(Measure.Name)) %>% 
  mutate(Measure.Name = if_else(Measure.Name == "General Anesthesia" & Denominator == "Vaginal Deliveries", "General Anesthesia (Vaginal)", Measure.Name)) %>% 
  mutate(Measure.Name = if_else(Measure.Name == "General Anesthesia" & Denominator == "Cesarean Deliveries", "General Anesthesia (Cesarean)", Measure.Name)) %>% 
  mutate(Measure.Name = if_else(Measure.Name == "Spinal Anesthesia" & Denominator == "Vaginal Deliveries", "Spinal Anesthesia (Vaginal)", Measure.Name)) %>% 
  mutate(Measure.Name = if_else(Measure.Name == "Spinal Anesthesia" & Denominator == "Cesarean Deliveries", "Spinal Anesthesia (Cesarean)", Measure.Name))

measures_df <- maternity_df %>% select(1, 3, 4, 6, 9) %>% 
  pivot_wider(names_from = Measure.Name, values_from = Count) %>% 
  mutate(Year = as.factor(Year)) %>% 
  mutate(Hospital.County = as.factor(Hospital.County)) %>% 
  filter(Hospital.County != "Statewide")

hospitalnames_df <- maternity_df %>% group_by(Hospital.Name) %>% count() %>% select(1)

write.csv(hospitalnames_df, "hospitalnames.csv")
```

```{r}
library(leaflet)
hospitalgeocode_df <- read.csv("data/hospitalsgeocode.csv", strip.white = TRUE)

hospitalgeocode_df <- hospitalgeocode_df %>% separate(Place, into = c("Hospital", "State"), sep = ",")

awesome <- makeAwesomeIcon(
  icon = "ios-clos",
  iconColor = "black",
  markerColor = "blue",
  library = "ion"
)

leaflet(hospitalgeocode_df) %>% 
  addTiles() %>% 
  addProviderTiles(providers$Wikimedia) %>% 
  addAwesomeMarkers(lng = hospitalgeocode_df$lon, lat = hospitalgeocode_df$lat, 
             popup = hospitalgeocode_df$Hospital, 
             icon = awesome)
```

```{r}
measuresloc_test <- read.csv("data/measuresloc.csv", check.names = FALSE)
```
