---
title: "Map Functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Practicing a function to create an interactive Leaflet map

```{r}
measuresloc_df <- full_join(measures_df, hospitalgeocode_df, by = c("Hospital.Name" = "Hospital"))

measuresloc_df <- measuresloc_df %>% filter(Hospital.County != "Rest of State")

write.csv(measuresloc_df, "measuresloc.csv")

measuresloc_df <- read.csv("data/measuresloc.csv")

library(leaflet)

awesome <- makeAwesomeIcon(
    icon = "ios-clos",
    iconColor = "black",
    markerColor = "blue",
    library = "ion"
)

awesome2 <- makeAwesomeIcon(
  icon = makeIcon(iconUrl = "https://gizmobrewworks.com/wp-content/uploads/leaflet-maps-marker-icons/hospital-2.png", 
                  iconWidth = 36, 
                  iconHeight = 36),
  iconColor = "black",
  markerColor = "blue",
  library = "ion"
)

awesome3 <- makeIcon(
  "https://gizmobrewworks.com/wp-content/uploads/leaflet-maps-marker-icons/hospital-2.png", 
                  iconWidth = 18, 
                  iconHeight = 18
)

## this will be used to create a reactive data set in the shiny app
measuresloc_2008 <- measuresloc_df %>% filter(Year == 2008) %>% 
  select("Episiotomy", Year, lat, lon, Hospital.Name)

leaflet(measuresloc_df) %>% 
  addTiles() %>% 
  addProviderTiles(providers$Wikimedia) %>% 
  addMarkers(lng = measuresloc_2008$lon, lat = measuresloc_2008$lat, 
             popup = paste(measuresloc_2008$Hospital.Name, "<br/>", 
                           measuresloc_2008$Episiotomy), 
                    icon = awesome3)

leaflet(measuresloc_df) %>% 
  addTiles() %>% 
  addProviderTiles(providers$Wikimedia) %>% 
  addAwesomeMarkers(lng = measuresloc_df$lon, lat = measuresloc_df$lat, 
                    popup = paste(measuresloc_df$Hospital.Name), 
                    icon = awesome, 
                    layerId = measuresloc_df$id)
```

```{r}
library(plotly)
library(tidyverse)

## line plot:
measuresloc_var <- measuresloc_df %>% select(Year, Hospital.Name, "Episiotomy")

line_hospital <- measuresloc_var %>% filter(Hospital.Name == "Adirondack Medical Center-Saranac Lake Site")

ggplot(data = measuresloc_var, aes(x = Year, y = Episiotomy, group = Hospital.Name)) + 
  geom_line() + geom_line(data = line_hospital, aes(x = Year, y = Episiotomy), colour = "red")

ggplotly(g, tooltip = "label")
```

```{r}
library(plotly)
## first scatterplot:
measuresloc_var <- measuresloc_df %>% select(Year, Hospital.Name, "Episiotomy", Hospital.County)

xvar <- measuresloc_var %>% filter(Year == 2008)

yvar <- measuresloc_var %>% filter(Year == 2011)

both_df <- full_join(xvar, yvar, by = "Hospital.Name")

g1 <- ggplot(data = both_df, aes(x = both_df[[3]], y = both_df[[6]])) + geom_point(aes(colour = both_df[[4]], text = paste("<br>", Hospital.Name, "<br> County: ", both_df[[4]])))

ggplotly(g1, tooltip = "text")
```

```{r}
## second scatterplot:
g2 <- ggplot(data = measuresloc_2008, aes(x = Episiotomy, y = Analgesia)) + 
  geom_point(aes(label = Hospital.Name)) + xlim(0, 1500) + ylim(0, 1500) + geom_smooth(se = F)

ggplotly(g2, tooltip = "label")
```

```{r}
## install.packages("shinythemes")
```

```{r}
r <- c(8, 4, 6, 9)

y <- (1:r[1])
for(i in 2:4){
  y <- c(y, (1:r[i]), SIMPLIFY = FALSE)
}

z1 <- as.data.frame(y)
z1 %>% filter(y != 0)
```
